EXP_NAME: KoBERTSeg
SEED: 223

MODE:
    do_train: False
    do_test: True
    
DATASET:
    name: KoBERTSeg
    data_path: ../data/task2/
    PARAMETERS:
        max_word_len: 512
        window_size: 3

MODEL:
    modelname: kobertseg_task2
    PARAMETERS:
        window_size: 3
        finetune_bert: True
    CHECKPOINT:
        pretrained: True
        checkpoint_path: null

TRAIN:
    batch_size: 8
    num_workers: 12

LOG:
    log_interval: 1

RESULT:
    savedir: './saved_model'
    result_name: test_results
