EXP_NAME: HAN_w_freeze_w2e
SEED: 223
    
DATASET:
    name: HAN
    data_path: ../data/LabeledData/Part1
    saved_data_path: false
    PARAMETERS:  
        max_sent_len: 16
        max_word_len: 64

TOKENIZER: 
    name: mecab
    vocab_path: ./word-embeddings/glove/glove.txt
    max_vocab_size: 50000  

TRAIN:
    batch_size: 256
    num_workers: 12

RESULT:
    savedir: ../data/LabeledData/Part1
    dataname: 'HAN_s16_w64'
