BUILD:
  datadir: '../../data/origin_fake_news/Clickbait_Auto'
  savedir: '../../data/direct_exp/Part1/Clickbait_Auto'
  METHOD:
    name: 'ngram_title_category_select'
    sim_argmax_dir: '../../data/preprocessed/Clickbait_Auto/sim_argmax'
    morphs_extract_dir: '../../data/preprocessed/Clickbait_Auto/morphs'
    sim_matrix_type: 'title'
    morphs_type: 'nouns'

SPLIT:
  datadir: '../../data/origin_fake_news'
  savedir: '../../data/direct_exp/Part1'
  ratio:
    - 6 # train ratio
    - 2 # validation ratio
    - 2 # test ratio

SEED: 42