BUILD:
  datadir: '../../data/origin_fake_news/Clickbait_Auto' 
  savedir: '../../data/direct_exp/Part1/Clickbait_Auto'
  METHOD:
    name: 'sentence_embedding_contents'
    model_name: 'Huffon/sentence-klue-roberta-base'
    batch_size: 4
    device_num: 0

SPLIT:
  datadir: '../../data/origin_fake_news'
  savedir: '../../data/direct_exp/Part1'
  ratio:
    - 6 # train ratio
    - 2 # validation ratio
    - 2 # test ratio

SEED: 42