EXP_NAME: BTS
SEED: 223

MODE:
    do_train: False
    do_test: True
    test_list:
        - train
        - valid
        - test
    
DATASET:
    name: BTS
    data_path: ../data/LabeledData/Part1
    saved_data_path: ../data/LabeledData/Part1/BTS_w512
    PARAMETERS:
        max_word_len: 512

TOKENIZER:
    name: bert

MODEL:
    modelname: bts_task1
    PARAMETERS:
        pretrained_name: 'skt/kobert-base-v1'
        num_classes: 2
    CHECKPOINT:
        pretrained: True
        checkpoint_path: null

TRAIN:
    batch_size: 64
    num_workers: 12

LOG:
    log_interval: 10

RESULT:
    savedir: './saved_model'
    result_name: test_results
