EXP_NAME: BTS-sentence_embedding_contents
SEED: 223

MODE:
    do_train: True
    do_test: False
    
DATASET:
    name: BTS
    data_path: ../data/direct_exp/Part1 # news article directory
    data_info_path: ../data/direct_exp/Part1/sentence_embedding_contents # splitted csv file director
    saved_data_path: ../data/direct_exp/Part1/BTS_w512-sentence_embedding_contents
    PARAMETERS:
        max_word_len: 512

TOKENIZER:
    name: bert
    
MODEL:
    modelname: bts
    PARAMETERS:
        pretrained_name: 'skt/kobert-base-v1'
        num_classes: 2
    CHECKPOINT:
        pretrained: False
        checkpoint_path: null

TRAIN:
    batch_size: 8
    num_training_steps: 10000
    accumulation_steps: 1
    num_workers: 12
    use_wandb: True

LOG:
    log_interval: 1
    eval_interval: 1000

OPTIMIZER:
    lr: 0.00001
    weight_decay: 0.0005

SCHEDULER:
    warmup_ratio: 0.1
    use_scheduler: True

RESULT:
    savedir: './saved_model'
