EXP_NAME: BTS
SEED: 223

MODE:
    do_train: False
    do_test: True
    
DATASET:
    name: BTS
    data_path: ../data/task1/
    PARAMETERS:
        saved_data_path: ../data/task1/BTS_w512
        max_word_len: 512

TOKENIZER:
    name: bert
    pretrained_name: 'klue/bert-base'

MODEL:
    modelname: bts
    PARAMETERS:
        pretrained_name: 'klue/bert-base'
        num_classes: 2
    CHECKPOINT:
        pretrained: False
        checkpoint_path: ./saved_model/BTS/best_model.pt

TRAIN:
    batch_size: 64
    num_workers: 12

LOG:
    log_interval: 10

RESULT:
    savedir: './saved_model'
    result_name: test_results
