EXP_NAME: BTS
SEED: 223
    
DATASET:
    name: BTS
    data_path: ../data/LabeledData/Part1
    saved_data_path: false
    PARAMETERS:
        max_word_len: 512

TOKENIZER:
    name: bert

TRAIN:
    batch_size: 256
    num_workers: 12

RESULT:
    savedir: ../data/LabeledData/Part1
    dataname: 'BTS_w512'
