EXP_NAME: FNDNet_wo_freeze_w2e
SEED: 223

MODE:
    do_train: False
    do_test: True
    test_list:
        - train
        - valid
        - test
    
DATASET:
    name: FNDNet
    data_path: ../data/LabeledData/Part1/
    saved_data_path: ../data/LabeledData/Part1/FNDNet_w1000
    PARAMETERS:
        max_word_len: 1000

TOKENIZER: 
    name: mecab
    vocab_path: ./word-embeddings/glove/glove.txt
    max_vocab_size: 50000  
    
MODEL:
    modelname: fndnet_wo_freeze_w2e_task1
    freeze_word_embed: True
    use_pretrained_word_embed: True
    PARAMETERS:
        num_classes: 2
        vocab_len: 50002
        dims: 128
        embed_dims: 100
        dropout: 0.2
    CHECKPOINT:
        pretrained: True
        checkpoint_path: null

TRAIN:
    batch_size: 256
    num_workers: 12

LOG:
    log_interval: 10

RESULT:
    savedir: './saved_model'
    result_name: results