EXP_NAME: FNDNet_w_freeze_w2e
SEED: 223
    
DATASET:
    name: FNDNet
    data_path: ../data/direct_exp/Part1 # news article directory
    data_info_path: ../data/direct_exp/Part1/random_select # splitted csv file director
    saved_data_path: false
    PARAMETERS:
        max_word_len: 1000

TOKENIZER: 
    name: mecab
    vocab_path: ./word-embeddings/glove/glove.txt
    max_vocab_size: 50000  
    
TRAIN:
    batch_size: 256
    num_workers: 12
    use_wandb: True

RESULT:
    savedir: ../data/one-cycle/Part1
    dataname: 'FNDNet_w1000'