EXP_NAME: FNDNet
SEED: 223
    
DATASET:
    name: FNDNet
<<<<<<< HEAD
    data_path: ../data/labeled_fake_news/Part1 # news article directory
=======
    data_path: ../data/direct_exp/Part1 # news article directory
    data_info_path: ../data/direct_exp/Part1/sentence_embedding_contents # splitted csv file director
>>>>>>> 04b7ae4e9825729d357b7c32fa9c15e7f919f4e9
    saved_data_path: false
    PARAMETERS:
        max_word_len: 1000

TOKENIZER: 
    name: mecab
    vocab_path: ./word-embeddings/glove/glove.txt
    max_vocab_size: 50000  
    
TRAIN:
    batch_size: 256
    num_workers: 12
    use_wandb: True

RESULT:
<<<<<<< HEAD
    savedir: ../data/labeled_fake_news/Part1
    dataname: 'FNDNet_w1000'
=======
    savedir: ../data/direct_exp/Part1
    dataname: 'FNDNet_w1000-sentence_embedding_contents'
>>>>>>> 04b7ae4e9825729d357b7c32fa9c15e7f919f4e9
