datadir: '../data/labeled_fake_news/Part1' 
savedir: '../data/direct_exp/Part1'
METHOD:
  name: 'sentence_embedding'
  target: 'content'
  select_name: 'sentence_embedding_content_category_select'

SEED: 42